
spring:
  application:
    name: seata-account
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://120.79.48.191:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    max-wait: 60000
    max-active: 100
    min-idle: 10
    initial-size: 10




seata:
  enabled: true
  application-id: seata-account
  tx-service-group: my_test_tx_group
  config:
    type: nacos
    nacos:
      group: SEATA_GROUP
      serverAddr: 127.0.0.1:8848
      username: "nacos"
      password: "nacos"
      namespace:
  registry:
    type: nacos
    nacos:
      group: SEATA_GROUP
      namespace:
      username: "nacos"
      password: "nacos"
      application: seata-server #TC的实例名称
      server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.hinz.seata.entity
  global-config:
    db-config:
      field-strategy: not-empty
      id-type: auto
      db-type: mysql
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    auto-mapping-unknown-column-behavior: none
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl